version: '3.7'
services:
  api-server:
    build: .
    tty: true
    restart: always
    ports:
      - '38000:3000'
    volumes:
      - ./app:/api-server
  db:
   image: mysql/mysql-server:8.0.30
   environment:
     MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
     MYSQL_DATABASE: ${DATABASE}
     MYSQL_USER: ${USER_NAME}
     MYSQL_PASSWORD: ${USER_PASSWORD}
   ports:
     - '33306:3306'
   volumes:
     - ./mysql/seed:/docker-entrypoint-initdb.d # 初期データ
     - ./mysql/db:/var/lib/mysql # 永続化
